### ISSUE TITLE
Replicate Arduino Slave behaviour

### ISSUE THREAD

**Issue by gbkwiatt** [hideakitai/ESP32SPISlave#47]
I am struggling to get this right. 
I have simple logic that I need to follow, and I know the code for Arduino, but I can't figure out how to do it with slave driver on esp32. 

any chance you can help ? @hideakitai 

Logic is as follow: 

- setup slave SPI(FSPI) with only MISO,CS,SCK attached 
- when CS goes low, start listening for SPI interrupts ( this is where I don't know how to set it up)
- I need  to count each clock pulses and send data on each pulse accordingly
- when CS goes high - reset the pulse counter 
- repeat ...

here is arduino code
```cpp
void setup() {
  //Serial.begin(115200);           //  setup serial (debug only)

  // have to send on master in, *slave out*
  pinMode(MISO, OUTPUT); //Pin 12
  pinMode(SS, INPUT);  //Pin 10
    //intitialize pull counter
  pullcount = 0; 

  // turn on SPI in slave mode
  SPCR |= _BV(SPE);

  // turn on interrupts
  SPCR |= _BV(SPIE);
    //interrupt routine on pin 2, calls resetCount function on falling edge of SS signal
  //without this call, the analog data doesn't initialize in the proper order
  //RISING has been required for some users, investigation ongoing
  attachInterrupt(0, resetCount, FALLING); 
  
  void resetCount()
{
  pullcount = 0; 
  SPDR = buttonbit1; //byte 1 buttons
}

// SPI interrupt routine
//This interrupt is called everytime SPI transfer is called from the master
ISR (SPI_STC_vect)
{


 if (pullcount == 0) // byte 2 buttons
    {
      SPDR = buttonbit2; 
      pullcount++; 
    }
    else if (pullcount == 1) //byte 3 buttons
    {
      SPDR = 255;
      pullcount++; 
    }
    //... and on 
    }
}
```

I really can't understand how can I achieve the SPI interruption bit with this library

**Comment by hideakitai** [comment]
If you are not using my library, I suggest you ask on the Arduino Forum.

**Comment by hideakitai** [comment]
The use of interrupts in this issue is not related to the contents of my library (and [spi slave driver](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/peripherals/spi_slave.html)) but to the use of interrupts in general. I wonder if adding interrupt functionality to pins with SPI assigned to them is possible, so I suggest asking on the Arduino Forum.

**Comment by gbkwiatt** [comment]
> The use of interrupts in this issue is not related to the contents of my library (and [spi slave driver](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/peripherals/spi_slave.html)) but to the use of interrupts in general. I wonder if adding interrupt functionality to pins with SPI assigned to them is possible, so I suggest asking on the Arduino Forum.

I think you're missing the point. The interrupt is the SPI interrupt 

SPI_STC_vect is a Serial Transfer Complete interrupt vector

Which I believe has equivalent in esp32 slave driver, and that was the question about. So it is related to your library and it is related to esp32 slave library.

I think `post_setup_cb` and `post_trans_cb` are those interrupts but I am not sure how to use it in you're library.

**Comment by hideakitai** [comment]
> SPI_STC_vect is a Serial Transfer Complete interrupt vector

I think what you'd like to do is not covered by the ESP-IDF's SPI slave driver. Because `post_setup_cb` is just a `Callback called after the SPI registers are loaded with new data.` and `post_trans_cb` is a `Callback called after a transaction is done`.

https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/peripherals/spi_slave.html#_CPPv4N28spi_slave_interface_config_t13post_setup_cbE

The lower-level interrupts are not supported in this library, and I'm unfamiliar with them. So, I suggested asking on the Arduino Forum.

> I think post_setup_cb and post_trans_cb are those interrupts but I am not sure how to use it in you're library.

Did you see this example?

https://github.com/hideakitai/ESP32SPISlave/blob/main/examples/transfer_in_the_background_with_cb/transfer_in_the_background_with_cb_slave/transfer_in_the_background_with_cb_slave.ino
